### ISSUE TITLE
Reserved username

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#101]
We need to prevent user from register with a "reserved" username. Here's some references where we can find such list:
- http://blog.postbit.com/reserved-username-list.html
- https://gist.github.com/caseyohara/1453705
- https://gist.github.com/mahemoff/2314663

**Comment by jdupl** [comment]
Est-ce qu'on a vraiment besoin de se protéger de ça?
C'est utile quand tu offres des domaines custom avec le username, mais ça ne nous impacte pas vraiment.

**Comment by fxleblanc** [comment]
Je peux le faire pour m4. @pgrenaud, tu prendrais quelle liste? Honnêtement, une liste suffira. Aussi, je propose qu'on fasse un fichier reserved-names dans backend/templates.

**Comment by jdupl** [comment]
@petit-prince j'aimerais en premier qu'on discute de si on veut vraiment cette feature.

**Comment by fxleblanc** [comment]
@jdupl Ça peut éviter les trolls. Si jamais quelqu'un fait ça, on va être obligé de le delete manuellement dans la database. Vite de même, c'est le use case que je vois mais y'en a sûrement d'autres. Je me fie à @pgrenaud pour ça. Je suis curieux de savoir.

**Comment by jdupl** [comment]
Y'a très peu de choses que ça protège. 
Ces listes sont faites pour protéger des utilisateurs légitimes des string. On en fait aucune.

**Comment by S0yKaf** [comment]
Je propose plutot qu'on est un minimum/maximum de longueur pour les pseudo, ca évitairais des affaires super longs ou super court, qui auraient pas rapport.

donc dissons qu'un username c'est de 3 à 25 chars, pour etre genereux

**Comment by sbstp** [comment]
Bin peut-être oui, mais une liste plus courte, genre "admin", "administrator", "administrateur", des trucs qui ont l'air officiels.

**Comment by S0yKaf** [comment]
:+1: @SBSTP

**Comment by sbstp** [comment]
Mais AFAIK les gens peuvent pas s'envoyer de messages, alors ya pas bcp d'abut qui peut arriver. Tu peux pas recevoir un message de "admin" qui te demande ton mot de passe.

**Comment by jdupl** [comment]
Y'a pas de messages qui peuvent s'envoyer.

**Comment by jdupl** [comment]
J'avais mal lu sbstp. :+1: pour un check sur la longueur du user.

**Comment by jdupl** [comment]
Donc on rescope l'issue à vérifier seulement la longeur ?

**Comment by fxleblanc** [comment]
:+1: pour la longeur du user.

**Comment by pgrenaud** [comment]
Peut être que vérifier le username n'est pas important maintenant, mais ça va l'être plus tard. On peut toujours repousser cette issue, mais j'aimerais la garder ouverte pour qu'on ne l'oublie pas.

Mais oui, on peut toujours vérifier la longueur. Ça serait le minimum à faire tant qu'à moi.
