### ISSUE TITLE
Split games in 2 separate sections

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#104]
Split games in 2 separate sections, one for PC and the other for Console.

**Comment by sm-Fifteen** [comment]
How about splitting PC games as well, something like "Bring your own copy" (DRMd in some way) vs "We got you covered" (DRM-free or outright free).
That way, people would know in advance what games they need to buy before the LAN.

**Comment by pgrenaud** [comment]
Je pourrais ajouter une icon pour indiquer quels jeux sont gratuits/payants. Mais je ne pense pas splitter d'avantage.

**Comment by sm-Fifteen** [comment]
Non, mais mettons UT2004. Le jeu est payant, mais on l'a DRM-free. Est-ce qu'on le catégorise come "Gratuit" ou "Payant"? C'est pour ça que gratuit devrais inclure "Fourni" ou "DRM-Free", ou au moins rendre ça plus clair.

**Comment by pgrenaud** [comment]
@Riboshom On n'assure plus la distribution de jeu standardisé.

**Comment by fxleblanc** [comment]
@pgrenaud D'accord avec toi, mais quels seraient les impacts sur la bakend?

**Comment by jdupl** [comment]
Il faudrait un gamtype dans les jeux. 
On pourrait en profiter pour mettre le gameid tout de suite aussi.

**Comment by fxleblanc** [comment]
:+1: pour le game type @jdupl. Pour le game_id, tu pensais à quoi, un nombre incrementé?

**Comment by jdupl** [comment]
game_id serait un id lisible pour les humains.
`ttt` Trouble in Terrorist Town
`css` Counter-Strike source 
etc.

**Comment by fxleblanc** [comment]
:+1: pour un game id avec trois lettres. Je peux faire le backend. Maintenant, est-ce qu'on veut modifier le frontend et de quelle façon?

**Comment by jdupl** [comment]
Ben pour séparer il faut un game_type aussi. 
Le frontend doit avoir une section jeux console et jeux PC.
Avant de faire cette issue, il faut fix la config.

**Comment by pgrenaud** [comment]
Pour le séparer, j'aurais carrément fait deux array différent, un pour PC et l'autre Console. Ça simplifierait l'itération coté client.

**Comment by fxleblanc** [comment]
Ok, je vais faire le server side. @pgrenaud, tu pourrais faire le frontend directement sur ma branche pour être constant. Je vais me mettre assigned mais tu fais partie du projet.

**Comment by jdupl** [comment]
non y'a pas de même branche qui se donne @petit-prince

**Comment by jdupl** [comment]
@petit-prince patrick va refactor la config avant que tu fasses la partie backend.

**Comment by pgrenaud** [comment]
Avant qu'on se lance, est-ce que quelqu'un peut faire un sample de la config proposer pour cette issue directement ici dans un code bloc pour qu'on confirme avec tout le monde?

**Comment by fxleblanc** [comment]
Ok pour un refactor de la config. @pgrenaud je vais t'assign pcq tu vas faire le frontend et la config apparement.
