### ISSUE TITLE
Code style cleanup

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#108]
Format code against a common syntax.

I propose https://github.com/airbnb/javascript

**Comment by fxleblanc** [comment]
## Conventions

@pgrenaud, pour l'instant, voici le jshintrc que j'utilise:
https://github.com/jshint/jshint/blob/master/examples/.jshintrc
Selon moi, c'est pas mal complet et standard(à moins que tu me prouves le contraire).
Au final, on en revient à utiliser

```
grunt lint ou grunt lint-watch
```

## Code style

Pour le code style, je me fie à:
http://sideeffect.kr/popularconvention/#javascript

**Comment by pgrenaud** [comment]
@petit-prince La page que tu as link pour le codestyle est vraiment loin d'être complète. Est-ce que tu as lu le lien que j'ai link dans mon premier post ?

**Comment by pgrenaud** [comment]
One thing I can think of, always use single quote for string: https://github.com/airbnb/javascript#strings

**Comment by pgrenaud** [comment]
Always use named function: https://github.com/airbnb/javascript#naming-conventions (scroll down a bit)

**Comment by fxleblanc** [comment]
Ok, je m'occupe de ça. Pour les named functions, @pgrenaud confirme que tu veux:

```
function something(args)
```

**Comment by pgrenaud** [comment]
Comme on a discuter ensemble, on va attendre après le LAN avant de procéder au refactor.

Pour te répondre @petit-prince, il faut remplacer ça:

```
var something = function(args) { };

exports.somewhat = function(args) { };
```

Par ça:

```
function something(args) { }

exports.somewhat = function somewhat(args) { };
```

**Comment by pgrenaud** [comment]
Keep open for now please.

**Comment by fxleblanc** [comment]
Je vais mettre cette issue-là closed. Si jamais vous trouvez du codestyle pas bon, indiquez-le dans une nouvelle issue pour que ça soit plus propre.
