### ISSUE TITLE
Page de FAQ

### ISSUE THREAD

**Issue by S0yKaf** [lanmomo/lanmomo-website#113]
les gens vont surement avoir plusieurs questions, nous pourrons regrouper les plus demandé sur une page de FAQ

**Comment by pgrenaud** [comment]
Bonne idée. Pour chaque question que vous recevez, incrivez-les ici.

**Comment by S0yKaf** [comment]
Q: Pourquoi le numéro de Téléphone?
R: C'est le college qui l'exige pour les gens qui vont rester la nuit. (plus de détails a venir)

**Comment by pgrenaud** [comment]
Q: Je ne peux pas m'inscrire à la fois PC et Console! Pourquoi?
R: Voir #118

**Comment by S0yKaf** [comment]
Q: Est-ce qu'on peut entrer et sortir du cegep passé 23h ?
R: À venir...

**Comment by sbstp** [comment]
Q: Tout ce qui est bouffe/breuvage. Combien devrais-je amener d'argent, ou combien de repas prévoir, etc.

**Comment by RickyNotaro** [comment]
Q: Est-t'il possible de venir seulement une seule des deux journées ? 
R: ?

**Comment by pgrenaud** [comment]
Q: Qu'est-ce que ça veut dire F.A.Q. ?
R: Acronyme pour "Foire Aux Questions" ou encore "Frequently Asked Question" en anglais.

**Comment by S0yKaf** [comment]
@pgrenaud

:leaves:

**Comment by pgrenaud** [comment]
Je vais commencé le template pour cette page, mais on va attendre d'avoir plus de contenu avant de la mettre en ligne.

**Comment by jdupl** [comment]
Moi je la mettrais le plus vite possible même s'il manque du contenu.

**Comment by pgrenaud** [comment]
Dans ce cas, ça serait bien d'avoir les réponses aux questions que l'on a jusqu'à maintenant.
