### ISSUE TITLE
Impossible de s'inscrire comme joueur console

### ISSUE THREAD

**Issue by sm-Fifteen** [lanmomo/lanmomo-website#115]
Lorsq'on tente de s'inscrire comme joueur console, le site défend à l'utilisateur de s'inscrire sous prétexte qu'il ne reste plus de sièges console, peu importe le nombre maximum de joueurs et le nombre de joueurs déjà enregistrés.

**Comment by fxleblanc** [comment]
Pourrais-tu donner ton json payload?

**Comment by sm-Fifteen** [comment]
@petit-prince :
    {"username":"xXxBOX360NOSCOPExXx",
    "firstname":"Console",
    "lastname":"Peasant",
    "phone":"450 555-5555",
    "type":"console",
    "email":"pomf@cock.li"}

**Comment by jdupl** [comment]
bogue confirmé :I

**Comment by fxleblanc** [comment]
## Problème

Il s'agit d'une erreur lors de la recherche du compte des utilisateurs inscrits. En gros, lorsque mongoose fait dans backend/controllers/users.js -> verifyMaximum:

```
User.where({active:true}, {type:type}).count().exec()
```

il ne fait pas une condition $and, il fait juste aller chercher le compte des utilisateurs actifs sans vérifier le type de compte. Étant donné que le nombre de participants actuel est de 16 et que le max de joueurs en console est de 15, un joueur qui essaie de s'inscire maintenant avec le type console va avoir l'erreur.

## Solution

http://mongoosejs.com/docs/api.html#query_Query-and
http://docs.mongodb.org/manual/reference/operator/query/and/
