### ISSUE TITLE
Not possible to register as both a PC and a Console player

### ISSUE THREAD

**Issue by sm-Fifteen** [lanmomo/lanmomo-website#118]
As there is not a "PC + Console seat" option for new subscribers, one needs to register twice to have access to both parts of the LAN if they don't intend to play on PC the whole time. However, since the email and username fields are marked as unique, they also need to pick a new username and a new email. Obviously, this is far from optimal. Shouldn't there be a way for players to join both the PC and console groups?

**Comment by jdupl** [comment]
Ben si tu viens PC, tu t'inscris PC et joue principalement à PC. Y'a personne qui va empêcher les joueurs de PC d'aller visiter les paysans, mais idéalement faut pas que la place PC soit vacante trop longtemps pour rien.

Encore là, si tu t'inscris pas dans `console`, rien ne garantie qu'il va y avoir de la place dans les consoles pour toi.

**Comment by pgrenaud** [comment]
^ this. Et pour être plus direct que @jdupl, oui tu ne peux pas choisir les deux et c'est voulu. Comme justin à dit, si tu veux jouer les deux, prend une place PC et pray pour qu'il reste de la place dans Console. Tu ne peux pas et tu ne dois pas t'inscrire dans les deux. Aussi, si tu compte jouer au deux, comme justin a dit, on s'attend que tu sois un minimum de temps à ton PC.

Je close la issue à wontfix si personne s'oppose. À rajouter dans la FAQ cette histoire là.
