### ISSUE TITLE
Termes et conditions

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#121]
Selon le [grand dictionnaire terminologique de la langue française du gouvernement québécois](http://www.granddictionnaire.com/ficheOqlf.aspx?Id_Fiche=8376555), il faudrait changer `termes et conditions`.

**Comment by pgrenaud** [comment]
Il faudrait le changer pour ... ?

**Comment by jdupl** [comment]
On peut choisir le plus approprié parmi les termes privilégiés sur la page.
