### ISSUE TITLE
Éviter le merge manuel de la configuration

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#124]
## Le problème

Lors d'un ajout dans la config, il faut présentement que je merge manuellement du JSON sur le serveur de prod à la main. 
C'est un processus fastidieux et sujet aux erreurs (directement en prod !).
## À modifier

Je propose donc une config qui contient tout ce qui n'est pas secret et qui serait mergée automatiquement.

La config privée aurait encore le principe du skel et qui fait charger dynamiquement selon le NODE_ENV.

Cette config publique contiendrait: `types, maximum, games, log`

Afin d'inclure log, il faudrait un if qui applique le level à info si NODE_ENV est à `prod`.

Sinon, une config à part peut être faite pour le log telle que `config.log.NODE_ENV.js`.
## À enlever

Aussi, la section
 `server: {
hostname: 'localhost',
port: 3000
},` n'est pas vraiment utile. `hostname` n'est jamais utilisé dans le code et port reste toujours 3000.
### Extra

Un dernier détail tant qu'à y être; les string single quotes `devraient` (selon moi) être remplacées par des doubles afin de ne pas avoir à protéger les `'`.

**Comment by fxleblanc** [comment]
Pas de trouble.

**Comment by fxleblanc** [comment]
Je propose qu'on renomme le fichier config.js à config.common.js car c'est ce fichier là qui fait une aggrégation de tous les autres fichiers.

**Comment by jdupl** [comment]
config.js ne servirait qu'à charger config.common.js et config.NODE_ENV.js selon moi.

**Comment by fxleblanc** [comment]
@pgrenaud @jdupl, pour le log, à partir des propositions que @jdupl a fait, je propose qu'on hardcode le pattern dans backend/lib/logger.js pour enlever du stock dans la config et que comme @jdupl proposait, on fasse un fichier de config séparé config.log.js qui contiendrait simplement le log level. Le fichier config.js ferait un require dessus et le level changerait en fonction NODE_ENV.
