### ISSUE TITLE
Bug while registering with the same email while the letter case is different.

### ISSUE THREAD

**Issue by RickyNotaro** [lanmomo/lanmomo-website#126]
## Bug while registering with the same email while the letter case is different.

If a user try to register with the email eXemplE@doMain.ltd while exemple@domain.ltd is already used, they will not receive an error message **but** they will not receive an email confirmation. 
### solution

Apply a `.toLowerCase` function in the backend before verifying the email in the database.

**Comment by RickyNotaro** [comment]
Just noticed that's it's the same thing with the `Nom d'utilisateur` field.

**Comment by pgrenaud** [comment]
Faut vraiment trouver une solution viable pour ça. Je suis vraiment habitué de travailler avec MySQL où les default collations (exemple `utf8_general_ci`) sont case insensitive. Se faisant, toute recherche faite dans la db est case insensitive (qui est le behavior normal que l'on doit s'attendre d'une db à mon avis).

Malheureusement, cela ne semble pas être le cas avec Mongo. En fait, le seul moyen de faire une recherche case insensitive est en [utilisant une regex](http://stackoverflow.com/a/1863452). Concrètement avec Mongoose, il faut [faire ceci](http://stackoverflow.com/a/9932470).

**Comment by pgrenaud** [comment]
Aussi, pour répondre à la solution proposé par @RickyNotaro, il n'est pas nécessairement approprié de simplement appliquer `.toLowerCase()` à l'adresse courriel. Comme on peut le lire sur [cette réponse](http://stackoverflow.com/a/9808332), la partie précédent le "@" est traité par le mailing système et son traitement est propre à ce dernier. Ce qui veut dire qu'il pourrait être case sensitive.

Donc, la meilleur solution serait de respecter la case dans laquelle les courriels ont été saisie, soit en les traitant de manière case insensitive (voir mon comment précédent).

**Comment by pgrenaud** [comment]
Aussi, on devrait ajouter [des méthodes statique au schéma](http://mongoosejs.com/docs/guide.html#statics) pour proprement faire ces recherche là. Et on devrait le faire avec toutes les query qu'on a actuellement (genre findActive(), countByType(type), etc.)

En exemple avec le cas qui nous intéresse:

```
userSchema.statics.findOneByEmail = function(email, cb) {
  return this.findOne({email: new RegExp('^' + email + '$', 'i')}, cb);
};
```

**Comment by fxleblanc** [comment]
@pgrenaud, oui pour les méthodes dans mongoose et oui pour la regex pour la recherche par email.

**Comment by pgrenaud** [comment]
@petit-prince donc oui pour tout ce que j'ai dit ou t'as des réserves pour qqch ? Sinon, questions, commentaires ?

**Comment by fxleblanc** [comment]
Aucun commentaire et aucune réserve à part que je suis partant pour le faire.
