### ISSUE TITLE
Lien vers les réseau sociaux dans le header ?

### ISSUE THREAD

**Issue by RickyNotaro** [lanmomo/lanmomo-website#131]
Je crois que les liens vers les comptes / événements sont un peu trop cachés et que l'on pourrais en mettre dans le header, à gauche de "inscription".

Bonne ou mauvaise idée?

**Comment by jdupl** [comment]
Faudrait trouver un design élégant. J'arrive pas vraiment pas à visualiser.

**Comment by RickyNotaro** [comment]
Quelque chose de ce style ? 

http://i.imgur.com/mm4aSdR.png

**Comment by jdupl** [comment]
J'aime ça. On va récolter les autres avis de @pgrenaud @Kiniamaro @petit-prince

**Comment by fxleblanc** [comment]
Bonne idée @RickyNotaro. Je mettrais ça dans m5.

**Comment by RickyNotaro** [comment]
Ou encore avec des couleurs: http://i.imgur.com/Sbv3yr8.png

**Comment by fxleblanc** [comment]
@RickyNotaro encore mieux. Tant qu'à faire des couleurs pour les réseaux, pourquoi pas en faire pour les icônes de jeux de participants?

**Comment by jdupl** [comment]
Effectivement, il faudrait que les autres icônes aient une couleur sinon
c'est inconsistant. On pourrait trouver une couleur pour toutes les icônes
(sauf celles qui ont des vraies couleurs).

**Comment by S0yKaf** [comment]
moi je metterais ca dans le footer

**Comment by pgrenaud** [comment]
J'ai complètement oublier de comment sur celui là. J'ai déjà mis des liens vers les réseaux sociaux dans la page de contact. Évidement c'est insuffisant. J'aimerais en rajouter et rendre ça plus présent, mais je ne pensais pas à des liens, mais carrément aux widgets ([facebook](https://developers.facebook.com/docs/plugins/like-button) et [twitter](https://dev.twitter.com/web/follow-button)).

Par contre, je vais devoir aller chercher de l'inspiration, car je ne sais pas du tout où mettre ça. Si notre première page c'était des news, ça aurait été beaucoup plus facile de l'intégré dans le UI (ça serait cool un jour avoir une pages pour des news en passant). Donc, dites-moi si vous êtes d'accord avec les widgets et je vais regarder comme les intégrés.

**Comment by RickyNotaro** [comment]
Je suis d'accord pour les widgets, mais je ne me souviens plus pour quelle raison, mais j'avais besoin d'aller sur la page de l'événement Facebook et ça m'avais pris vraiment trop de temps pour la trouver sur le site web que j'ai finalement décidé de la rechercher directement sur Facebook.

Envoyé de mon iPhone

**Comment by jdupl** [comment]
Moi ça me fait chier les widget de réseau sociaux...

**Comment by pgrenaud** [comment]
Self note: Ajouter un info/well sur la page d'inscription et de confirmation pour diriger vers l'événement facebook.
