### ISSUE TITLE
Disable subscrition when full

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#136]
When the player maximum will be reached, the subscription page will still display a subscription form, which will confuse the users making them think that the subscription is still possible.

Change that behavior, so the subscription page hide the form and display a message explaining that the maximum number of player was reached.

**Comment by jdupl** [comment]
Il faudrait tout de même laisser les gens s'inscrire si jamais des places se libèrent.

**Comment by pgrenaud** [comment]
Je dis pas le contraire. Moi je pensais à de quoi de dynamique/automatique, pas hardcoder. Pas contre, tu sous-entends qu'on donne un moyen pour se désister aux participants, ce qui n'est pas le cas. Est-ce qu'on devrait faire quelque chose pour ça ?

**Comment by jdupl** [comment]
Ben on peut envoyer un courriel ~2 semaines avant le lan afin de savoir si
des gens ne veulent plus venir.
Le 2015-03-27 2:39 PM, "Patrick Gagnon-Renaud" notifications@github.com a
écrit :

**Comment by jdupl** [comment]
Pour le prochain lan on aura le temps de faire des comptes où que les gens peuvent se déinscrire.

**Comment by pgrenaud** [comment]
Indeed. Ça serait peut être bien qu'on commence à discuté quelque part des features majeurs qu'on veut ajouter, genre un vrai compte utilisateur pour séparer le user d'un participant. Comme c'est assez gros comme discussion, c'est où la meilleur place pour ça ?

**Comment by jdupl** [comment]
Je pense qu'on est mieux d'en reparler après le LAN qui s'en vient.
