### ISSUE TITLE
Page des serveurs

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#143]
Faire la page qui va contenir la liste des serveurs et leurs infos de base:
- nom du jeux/mod du serveur
- hostname et son ip.

Le backend devra enlever les serveurs qui n'ont pas redonné leur status depuis X temps.

**Comment by pgrenaud** [comment]
Peux-tu inscrire dans la description de cette issue la liste des informations qu'il faut afficher ?

**Comment by pgrenaud** [comment]
@jdupl Peux-tu inscrire dans la description de cette issue la liste des informations qu'il faut afficher ?

**Comment by jdupl** [comment]
Voir le [data envoyé](https://github.com/lanmomo/gameserver-notifier/blob/master/src/notifier.py#L15) par le notifier

**Comment by pgrenaud** [comment]
Je fais le frontend. Quelqu'un d'autre peut travailler sur le backend.

**Comment by jdupl** [comment]
@petit-prince si tu es intéressé

**Comment by pgrenaud** [comment]
@jdupl Est-ce que tu peux me dire qu'est-ce que repésente `game_id` exactement ? Est-ce que je peux m'en servir pour déterminé de quel jeu il s'agit ? Aussi, est-ce qu'on va toujours utiliser les ports par défaut pour les jeux correspondants ?

**Comment by pgrenaud** [comment]
@petit-prince Le frontend est prêt. Prend la branche `servers` pour pouvoir travailler. Quand tu auras fini, update cette branche pour que je puisse re-valider le UI et apporter des correctif nécessaire avant le PR.

Avant que j'oublie, je pense déjà ajouter une colonne "Dernière mise à jour". @petit-prince tiens en compte pour le backend et @jdupl dis moi ce que tu en penses.

**Comment by sm-Fifteen** [comment]
@pgrenaud `game_id` sert à déterminer de quel jeu la notification provient. C'est un string techniquement arbitraire, et le serveur derait être capable de handle ceux qu'il connait pas, mais so far on a `tm` (Trackmania), `kf` (Killing Floor), `tf2` (Team Fortress), `css` (Counter Strike Source), `csgo` (Counter Strike GO) et c'est possible qu'on en ajoute d'autres au besoin.

**Comment by sm-Fifteen** [comment]
@pgrenaud Pour les ports, @jdupl m'a assuré que toutes nos VM rouleraient sur le port par défaut.

**Comment by jdupl** [comment]
Pour les game id voir: https://github.com/lanmomo/server-templates/tree/master/servers
Prop hunt sera renommé ph.

**Comment by pgrenaud** [comment]
@petit-prince y reste juste le backend. mais ouin, en tant que tel, c'est pas mal fini.

**Comment by pgrenaud** [comment]
@jdupl Je suis en train de finaliser. Le token est supposé être envoyé comment au juste https://github.com/lanmomo/gameserver-notifier/blob/master/src/notifier.py ?

**Comment by fxleblanc** [comment]
@pgrenaud je pourrais faire le backend mais il faudrait savoir ce qu'il reste à faire. Il y a la route qui recoit le data et la route qui donne le data au front end. Quelles seraient les améliorations possibles? À la limite, tout ce que je vois, c'est enlever le FIXME en plein milieu du code.

**Comment by pgrenaud** [comment]
@petit-prince je suis en train de tout finaliser. Il me reste à updater le notifier. Mais essentiellement, tout était déjà là.

**Comment by fxleblanc** [comment]
Cool. Merci

Le 31 mars 2015 15:39, Patrick Gagnon-Renaud notifications@github.com a
écrit :
