### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#145]
Maintenant que le LAN est terminé, il serait important de faire un rétrospective de la situation actuelle et de déterminer si des refontes majeures s'impose.

Quelques exemples que j'ai en tête qu'il serait bien de discuter:
- Pour le backend, est-ce qu'on reste avec Node.js ou est-ce qu'on revient vers Django ?
- Renommer "subscription" pour "registration"
- Renommer "username" pour "nickname" (et "pseudonyme" en français)

Aussi, il serait bien de discuter des fonctionnalités que nous aimerions ajouter au site. Quelques exemples:
- Ajouter un vrai compte utilisateur, pour permettre à l'utilisateur de s'inscrire et se désinscrire comme il le souhaite au événement
- Ajouter un seat selector ?

**Comment by fxleblanc** [comment]
#160
#161
#162
