### ISSUE TITLE
Loading bar

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#147]
Puisque l'affichage de plusieurs pages dépend d'une ou plusieurs requêtes faites à l'API, je me suis dit qu'il serait intéressent de mettre en place quelque chose de standardiser dans le UI pour donner un feedback au user. En faisant une recherche rapide, je suis tombé sur une solution toute faite qui répond parfaitement à ce besoin.

Donc, j'ai ajouter le module `angular-loading-bar` qui écoute les events du services `$http` pour afficher automatiquement une barre de chargement pour chaque requête.

@jdupl Est-ce que tu pourrais faire pointé le serveur dev sur la branche `loading-bar` pour que je puisse évaluer les impacts sur le UI dans un environnement réel (pour déterminer si tout cela en vaut la peine avant de poursuivre) ?

**Comment by S0yKaf** [comment]
Comme sur youtube? Une bar au top de la page?

**Comment by pgrenaud** [comment]
Oui, c'est ce que ça donne en gros. Mais j'ai besoin de voir le résultat dans un environnement réel.

**Comment by S0yKaf** [comment]
- http://github.hubspot.com/pace/docs/welcome/

Je laisse ca ici au cas ou

**Comment by jdupl** [comment]
Ce n'était pas prévu pour m4 ça. J'aurais vraiment aimé qu'on finisse ce qu'on devait faire avant.
La branche loading-bar est sur le site de dev.
