### ISSUE TITLE
Progress bar from user page is broken on IE11

### ISSUE THREAD

**Issue by RickyNotaro** [lanmomo/lanmomo-website#153]
## Progress bar from user page not visible on IE11.

As seen on the screenshots, the progressbar is broken on Internet Explorer 11.
### Screenshots
- http://i.imgur.com/SUSfqEY.png
- http://i.imgur.com/gNXLwGX.png

**Comment by S0yKaf** [comment]
jpense que c un bug connu de bootstrap

**EDIT**
Bug connu de angular-bootstrap

**Comment by jdupl** [comment]
On supporte pas IE fin de l'histoire.
On pourrait mettre un pop-up si le user agent est IE (ou trident).

**Comment by S0yKaf** [comment]
un gros pop-up, "Get a real browser" qui pointe vers Firefox et chrome(ium) (en très petit)
