### ISSUE TITLE
Utiliser la liste des vues partielles pour générer une route plus propre

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#158]
```
app.get(/^\/(users|games|servers|about|terms|faq|contact|subscribe|congratulations)?$/,mainController.index);
```

**Comment by fxleblanc** [comment]
@jdupl, je pensais boucler à travers le dossier des partielles, cependant, si on sépare le dossier public du reste de l'application, l'app ne marchera plus. Est-ce une possibilité?

**Comment by jdupl** [comment]
On peu faire un seul fichier où mettre les urls et ça fait les routes ET la config nginx. Ça serait un peu mieux.

**Comment by fxleblanc** [comment]
config/urls.js?

On pourrait aussi faire une tâche Grunt pour générer le fichier.

**Comment by jdupl** [comment]
Oui le processsus serait fait dans un commit séparé.
Il faudrait un test qui regarde si tout est bon.

**Comment by fxleblanc** [comment]
#159
