### ISSUE TITLE
Compte utilisateur

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#161]
L'utilisateur, une fois inscrit pourrait:
- Modifier ses informations(à appronfondir)

**Comment by jdupl** [comment]
Je pense que les ventes seront finales pour ce LAN.

**Comment by fxleblanc** [comment]
Je vais transférer dans future, ca va demander plus de discussion, mais pas pour le LAN automne 2015.

**Comment by fxleblanc** [comment]
Nouvelle issue pour la conception du login. Voir #164
