### ISSUE TITLE
Selection des sièges

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#162]
L'utilisateur inscrit a la possibilité de choisir son siège en utilisant un widget interactif. Il faudra probablement réviser le modèle de l'utilisateur.

**Comment by sm-Fifteen** [comment]
La première à faire pour ça, ça va être de définir ce qu'on veux dire par "place". Présentement, ça a l'air parti pour être assez d'espace pour une tour et un écran bien paqueté (ou juste l'écran avec la tour par terre), de la place pour les bras, une chaise, 3 amps de courant (reste à savoir si on fournit les prises) et un port sur une de nos switchs.
Sachant ça, on doit définir l'espace à allouer (avec la marge acceptable) pour chaque place pis mapper ça sur le plan de tables.
Juste ça, ça nous aiderait à mieux définir notre setup pour le lan pis essayer de le tweaker pour minimiser le hustle au moment de tout déployer.
Les tables blanches qu'on utilise (ou en tout cas, les miennes) ont à peu près 76cm de profondeur, pis on met 2 ordis par table d'habitude. À 180 cm de largeur, ça nous fait des places de 90*76 cm par personne.

**Comment by S0yKaf** [comment]
ca a pas rapport @Riboshom, on cherche pas a savoir c quoi une place, on veut juste ajouter un champ ou une carte interactive qui va permetre a une personne de choisir un siege. parce que peut importe c quoi "une place" ca reste a la base, l'endroit ou une personne va s'assir

**Comment by jdupl** [comment]
On veut juste un sélecteur de siège... J'ai déjà défini tous ces paramètres lors du plan de la salle

**Comment by sm-Fifteen** [comment]
@Kiniamaro Si on veux un sélecteur, on a besion d'une carte avec des places, si on veux une carte ça nous prend des mesures pis si on veux des mesures, ça nous prend des définitions. Y'a pas de magie.
@jdupl Tu pourrais mettre des divisions en fonction de ça sur le plan?

**Comment by jdupl** [comment]
On va juste avoir une jpg avec les sièges. Le sélecteur de siège connait juste le ID de siège qui va de 1 à 96.

**Comment by sm-Fifteen** [comment]
Ça serait pas plus clean de juste superposer des divs sur le plan pis de donner des IDs à ces divs là qui correspondent aux sièges?

**Comment by jdupl** [comment]
wowowo non là
On va juste faire une jpg et tu tapes le siège que tu veux. Faut mettre ça en prod dans pas long.

**Comment by fxleblanc** [comment]
Une nouvelle issue de conception a été créée pour prendre en charge cette fonctionnalité. Voir #165
