### ISSUE TITLE
Page de login pour se connecter en tant qu'utilisateur

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#164]
## Backend

Rénovations sur le modèle:
- Ajout du champ de mot de passe
- Méthodes de hashage pour le mot de passe

Rénovations sur les routes:
- POST /api/login
- GET /api/profile
## Frontend

Rénovations sur le frontend:
- Page de login
- Page de profil de l'utilisateur

**Comment by jdupl** [comment]
Il faudrait que le profil comporte si un billet a été acheté.

**Comment by fxleblanc** [comment]
Je propose que lorsque l'utilisateur s'inscrit, il fasse les trois étapes en même temps:
- Rentrer ses informations
- Choisir sa place
- Faire le paiement du billet

Donc, on va assumer que l'utilisateur qui se connecte à son compte a déjà acheté ses billets. Pour la conception de comment le billet va être fait dans le backend, regarde #169.
