### ISSUE TITLE
Page de Code QR

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#169]
Lorsque l'utilisateur est inscrit, il va sur la page de code QR est génère son code à partir du hash de son billet. Cela implique que le hash soit généré lors de l'inscription et soit inséré dans le modèle de l'utilisateur.
## Backend

Changements dans le modèle user:
- Ajout du champ ticket
## Frontend

Modifications sur le frontend:
- Ajout de la vue partielle pour le code QR

**Comment by jdupl** [comment]
L'utilisateur voit son billet sous format de code QR sur son profil. Il peut télécharger l'image afin de l'apporter au LAN. 

Le code QR est un lien vers lanmomo.org/tickets/verify/<secret_uuid>

Ce lien donne des informations sur le type de billet, son numéro, son numéro du siège si applicable et le nom réel du propriétaire.

À l'entrée du LAN, ces informations sont vérifiées par les bénévoles à l’accueil.

**Comment by jdupl** [comment]
#196
