### ISSUE TITLE
Page de présentation du LAN

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#17]
## Page principale

On pourrait mettre des éléments informatifs sur la page principale tel que:
- Les règles du LAN
- Comment s'inscrire(je sais c'est très simple mais on ne peut jamais être assez clair)
- Comment utiliser l'interface du site(installer les jeux)

Le but est de simplement mettre du contenu pertinent pour les potentiels participants sur la page et je crois que cette issue servirait de centre d'idées pour cet objectif.

**Comment by pgrenaud** [comment]
Je pense que tous les points que tu as mentionné pourrait se retrouver sur des sections différentes du site.
- Règlements -> Page d'inscription
- Aide pour inscription -> Page d'accueil et/ou page d'inscription
- Aide pour les jeux -> Page des jeux

On a plus avantage à garder une belle page d'accueil et rediriger les utilisateurs vers les sections approprier sur les autres pages du site.

**Comment by pgrenaud** [comment]
Je close la issue puisqu'on a déjà une issue d'ouverte pour chacune de ces pages là.
