### ISSUE TITLE
Inscription et compte utilisateur

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#179]
## Inscription
- [x] form signup
- [x] confirmation par courriel
- [x] activer le compte
## Compte utilisateur
- [x] connexion
- [x] déconnexion
- [x] modification des infos du compte

**Comment by sbstp** [comment]
Pour assurer la synchronization et la validitée des données, l'inscription devrait être fait avec un lock exclusif sur la table des inscriptions. Cela va assurer qu'aucune inscription n'est ajouté entre le moment où on regarde le nombre d'inscription et l'insertion de l'inscription courante.

**Comment by jdupl** [comment]
L'inscription du compte utilisateur comme telle non, seulement la réservation de billet.

**Comment by sbstp** [comment]
Ouais, seulement le bout qui est limité par la quantité de personnes maximale.
