### ISSUE TITLE
Envoyer les emails en background

### ISSUE THREAD

**Issue by sbstp** [lanmomo/lanmomo-website#181]
Pour permettre une réponse rapide à une requête d'inscription, l'envoie de courriel devrait se faire en background et ne pas bloquer le thread courant.

De plus, l'envoie de courriel devrait être réessayé lors d'une erreur.
- 3 fois avec un timeout de 1 minute
- 10 fois avec un timeout de 15 minutes
- Si on arrive toujours pas à envoyer le courriel, logger l'erreur à quelque part

**Comment by jdupl** [comment]
Il manque le logging.

**Comment by jdupl** [comment]
@sbstp je vais commencer à migrer vers mailgun pour l'envoie de courriel à cause de hotmail....

**Comment by sbstp** [comment]
C'est ce que digital ocean a dit?

**Comment by jdupl** [comment]
Ça ou refaire la droplet avec une nouvelle ip... 
Rien garantie que l'ip va être clean. En plus ça fonctionnait y'a 1 semaine.

**Comment by sbstp** [comment]
Mailgun à l'air ok, avec notre volume ça devrait être free. Le seul probleme que je vois c'est que c'est propriétaire.

**Comment by jdupl** [comment]
yep

**Comment by sbstp** [comment]
On pourrait rajouter un param `backend` à `send_email` qui default à mailgun mais qui permet d'utiliser smptlib aussi.

**Comment by jdupl** [comment]
OK mailgun a vérifié le domaine lanmomo.org
Je peux envoyer jusqu'à 10k email par mois.
Hotmail met tout de même dans spam. Au moins, ça ne les bloque pas.

**Comment by sbstp** [comment]
Damn, ya tu des trucs qu'on peut faire pour pas se ramasser dans spam?

**Comment by jdupl** [comment]
Pas vraiment plus.
Gmail c'est direct dans la boite de réception.
