### ISSUE TITLE
Sélecteur de siège

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#184]
Faire le frontend pour le sélecteur de siège.

Pas de WS, juste du AJAX chaque n secondes et lorsque l'utilisateur sélectionne un siège.

Le back-end n'est pas encore implémenté, mais il faut prévoir le composants angular à utiliser.

@sbstp @Kiniamaro

**Comment by sbstp** [comment]
Jvais commencer à sketcher le front-end.
