### ISSUE TITLE
Choix de technologies

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#2]
TLDR: Après discussion, les technologies seront Django avec angular.js par AJAX et MySQL.

Je propose python comme backend et angular.js en frontend communiquant par des websockets.

**Comment by S0yKaf** [comment]
:+1:

**Comment by fxleblanc** [comment]
:+1: Si jamais vous êtes down pour nodejs, j'aurais préféré cette technologie-là.

**Comment by jdupl** [comment]
Je vois juste pas de raisons d'utiliser nodejs. Nous n'avons pas besoin d'async dans le backend.

**Comment by S0yKaf** [comment]
Je suis partant pour les deux mais je pense que python est le meilleur choix.

**Comment by sbstp** [comment]
Pk websockets? Est-ce ça a besoin d'être en temps réel? REST pas suffisant?

**Comment by jdupl** [comment]
Si quelqu'un réserve un siège tu dois le voir tout de suite (si des gens sont en train de réserver en groupe). 
On peut faire un ajax qui pool chaque seconde, mais c'est un peu lourd.

**Comment by sbstp** [comment]
Bin quand tu send ta request pour la place, ça valide bien qu'elle est libre. Mais si on fait dequoi avec de websockets, node est vrm mieux.

http://socket.io/

**Comment by jdupl** [comment]
C'est pour que les gens voient qu'une place est prise dès qu'elle est prise. 

Y'a juste le client qui deal avec des event async vraiment. Y'a en masse de libs faites en python pour juste push des notifications à angular.

**Comment by S0yKaf** [comment]
je catch pas trop le node hype, Django est parfait pour ce qu'on veut faire, ca a plein de feature qui vont nous sauver plein de temps, et justement on a quand meme un deadline tight

**Comment by sbstp** [comment]
Django fait pas de websockets. Django c'est un framework de routing et de rendering. Pas de realtime websockets.

**Comment by jdupl** [comment]
Ben alors on peut faire un AJAX simple. Les wb sont pas si vitales que ça.
L'important c'est de livrer le site au moins 1 mois avant le prochain LAN et de pouvoir le maintenir après.

**Comment by S0yKaf** [comment]
https://www.djangopackages.com/grids/g/websockets/ please

**Comment by sbstp** [comment]
Python à pas été designé avec la concurrence en tête. Va p-e devoir faire des lock/mutex, prob que ta pas avec node.

**Comment by jdupl** [comment]
SQL fait ça pour toi ?

**Comment by sbstp** [comment]
Les websockets passe pas par la DB.

**Comment by jdupl** [comment]
Tu fais juste lancer un event et ça refresh pour tout le monde.

**Comment by S0yKaf** [comment]
oui mais ce que je dit c'est est-ce qu'on a vraiment avantage a utiliser node? oui, les websockets ca irais mieu en node mais le reste? django a quand meme beaucoup de feature qui te permet de sauver beacoup de dev time.

faut penser, est-ce qu'on prefere utiliser des features de django pour sauver du temps ou creer notre site vraiment custom comme ont le veut en node, mais ca vas nous prendre le double du temps?

**Comment by jdupl** [comment]
Honnêtement, je pense que le site doit être prêt d'ici 3mois. On peut y aller sans wb.

**Comment by S0yKaf** [comment]
le plus tot le site est fait, le plus tot ont peut commencer a faire de la pub et avoir du monde qui sign up

**Comment by sbstp** [comment]
Moi je dit Django, fuck websockets, pi on verra plus tard.

**Comment by jdupl** [comment]
Ok @petit-prince tu en penses quoi ?

**Comment by S0yKaf** [comment]
donc tout le monde est d'accord pour django?

**Comment by jdupl** [comment]
Avec SQL ?

**Comment by S0yKaf** [comment]
je savais pas que SQL cetait une question, django c'est pas fait pour du nosql

**Comment by SBSTP** [comment]
SQL Server

**Comment by jdupl** [comment]
MariaDB.

**Comment by sm-Fifteen** [comment]
Django it is, I guess, j'ai pas ben plus d'Expérience en Python qu'en node au final. Je vais vous suivre.

**Comment by Kiniamaro** [comment]
no troll plez, this is serious talk :^)

**Comment by Riboshom** [comment]
SQL? Plez, on va pas revenir là dessus?

**Comment by jdupl** [comment]
Pour le frontend on choisit angular.js 1.3 ?

**Comment by sbstp** [comment]
Yea

**Comment by S0yKaf** [comment]
je dit rien je connais pas ca

**Comment by sm-Fifteen** [comment]
Utiliser du CheeseSQL, ça veux juste dire qu'on va avoir à se faire chier avec nos data models aux deux bouttes.

**Comment by S0yKaf** [comment]
@Riboshom non django fait pas mal toute pour toi coter relation

**Comment by jdupl** [comment]
J'ai enlevé les troll/sql comments. Ne le prenez pas personnel.

**Comment by sm-Fifteen** [comment]
Maxdup avait l'air de dire qu'on allait vraiment se faire chier à setup angular sur Django

**Comment by S0yKaf** [comment]
on verra

**Comment by jdupl** [comment]
ça a aucun rapport...

**Comment by sbstp** [comment]
someone setup the project

**Comment by sm-Fifteen** [comment]
@jdupl : De?

**Comment by jdupl** [comment]
@SBSTP check les [milestones](https://github.com/LanMomo/LanMomo-Website/milestones). 
Faudrait vraiment faire m1 avant m2. 
Aussi, on s'est pas entendu pour les tests. Avons-nous le temps pour du TDD ?

**Comment by S0yKaf** [comment]
c'est pas supposer sauver tu temps au finale du TDD ?

**Comment by jdupl** [comment]
À long terme

**Comment by fxleblanc** [comment]
+1 pour python et tdd.

**Comment by fxleblanc** [comment]
## Outil d'automatisation

Si jamais on doit automatiser les tests et de le déploiement, je propose qu'on utilise gruntjs. Voici les principaux avantages:
1. Configuration en JSON(everyone loves json)
2. Facilité d'utilisation
3. Indépendant de python

## Exemple concret

Prenons par exemple le lancement automatique des tests lorsque les fichiers changent, il suffit simplement de deux plugins:
- https://github.com/gruntjs/grunt-contrib-watch
- https://github.com/sindresorhus/grunt-shell

**Comment by jdupl** [comment]
Je suis d'accord pour automatiser les déploiments, mais je vais voir si je peux pas trouver un moyen de packager en .deb le site. Chez iWeb ils font ça et c'est très pratique. Grunt peut tout de même lancer toutes les tâches et déployer le .deb.

As-tu vérifié que c'est pas trop cheese appeler les tests en python de grunt ?

**Comment by fxleblanc** [comment]
Pour tout ce qui est test en python, unittest fera la job. Pour l'appel en console, il suffit simplement d'utiliser grunt-shell et donner une commande custom. Si on se fit au lien en-dessous, on peut même appeler une classe et une méthode de test spécifique. Il reste simplement à faire le lien avec grunt en utilisant grunt.option(voir le lien plus bas) afin de spécifier un test en ligne de commande. Sinon grunt test ou même grunt sans argument pourrait invoquer la test suite.
- http://gruntjs.com/api/grunt.option
- https://docs.python.org/2/library/unittest.html#command-line-interface
