### ISSUE TITLE
Allow user to change seat within timelimit

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#200]
Add a POST/UPDATE method in the backend to allow a user that would return on the seat picker page, in the checkout process, within the timelimit, to change his seat.

**Comment by jdupl** [comment]
Est-ce que `PUT /api/tickets/seat` te convient ? 
Comme body de PUT, il faudrait au minimum le nouveau id de siège.

**Comment by pgrenaud** [comment]
Well, c'est toi qui voit. J'ai même pas envie de regarder si ça match les autres URL, de peur de trouver de quoi qui fit pas et de me mettre à rewrite du code qui fonctionne parfaitement bien. Pour le body du PUT, pas de trouble. On a en effet pas besoin de send le vieux ID, sachant qu'on le sait déjà avec la session du user courant.
