### ISSUE TITLE
Nettoyer les owners des sièges

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#203]
Dans la map, les anciens owners ne sont pas nettoyé lors des requêtes AJAX.
 Il faut vider le tableau des owners lors de la mise à jour.

**Comment by pgrenaud** [comment]
Selon ce que j'ai pu constater, oui ils restent dans la table tickets, mais ils sont ignorés par les requêtes puisqu'ils sont outdated.

**Comment by jdupl** [comment]
Non je parle dans le state de l'app js.
Tu hover sur les sièges occupés précédemment (soit un billet a expiré ou a été changé) et le nom de la personne s'affiche...

**Comment by jdupl** [comment]
![](http://a.maro.xyz/YR0hOdB.png)

**Comment by pgrenaud** [comment]
Oh oh! Ok. Ça c'est ma faute.

**Comment by pgrenaud** [comment]
J'ai un fix. Je suis en train de tester.
