### ISSUE TITLE
Issues Louis

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#234]
## Login
- Message erreur connexion + plus du bouton de connexion
## Tickets
- Rendre plus clair que les réservations sont temporaires
- ~~Bouton achat mis en évidence même si l'utilisateur n'a pas de compte (le warning n'est pas visible/clair)~~
- ~~Lorsque l'utilisateur a acheté son billet, le status "disponible" doit devenir "acheté"~~
- Description sommaire de chaque type de billet (~~qu'est-que BYOC?~~ et préciser que PC a accès console)
## Acceuil
- Détails de l'heure et lieu plus précis (google maps ?)
- ~~Enlever le bouton "acheter mon billet" lors que l'utilisateur a un billet~~
## Tournois
- ~~Fuck up tournois (parfois ça marque pas de billet: causé par le manque de catch de l'event 'login')~~
- ~~Lien créer une équipe pour chaque jeux (pas juste en haut)~~
- Mot de passe pour join les équipes (nice to have)
- ~~Régles tournois (4 v 4 etc)~~
- Horaire tournois
## Signup
- ~~Conditions générales lien cliquable pas assez clair. Mettre un bouton.~~
## Profile
- ~~Changer le formulation "vous n'avez pas encore de billet"~~
## Map
- Tous les sièges libres devraient être verts
- Le siège sélectionné devrait être d'une couleur unique
- ~~Le carré avec le numéro du siège sélectionné devrait être vert, rouge, jaune (il reste gris)~~

**Comment by pgrenaud** [comment]
J'ai barré tout les items que j'ai déjà pris action pour corriger. Pour les autres, je n'ai pas l'intention pour l'instant de les corrigés. Il y a plusieurs raisons pour cela (que je peux fournir de manière détaillé si besoin), mais j'attends surtout d'avoir plus de feedback de d'autres personnes avant de prendre action.
