### ISSUE TITLE
Captain cannot delete team when there is still members inside

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#236]
When you try doing that, the request crash and the server reply with a 500 Internal server error.

**Comment by pgrenaud** [comment]
@Kiniamaro

**Comment by S0yKaf** [comment]
ok I'll remove the foreign keys in the model

**Comment by jdupl** [comment]
non supprime les données d'association

**Comment by S0yKaf** [comment]
-_- but I'm lazy

**Comment by jdupl** [comment]
ça va faire de la crap sinon

**Comment by S0yKaf** [comment]
c'est fait, c'etait 2 ligne a ajouter meme la :^)

**Comment by S0yKaf** [comment]
#244
