### ISSUE TITLE
Team member cannot leave team on there own

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#237]

**Comment by pgrenaud** [comment]
@Kiniamaro

**Comment by S0yKaf** [comment]
yeah they can?

**Comment by pgrenaud** [comment]
Qu'est-ce que je dois call de mon bord pour que ça marche? Parce que quand j'ai essayer de call `deleteTeamUser(id)` (`DELETE /api/team_users/{id}`) ça me retourne une erreur (que je me souviens plus).

**Comment by S0yKaf** [comment]
pourtant, je fait `if team.captain_id != user_id and user_id != id:` dans le delete, donc si tu essaye de te kick toi meme, ca devrais pas rentrer dans cette condition la et donc deleter l'user

**Comment by S0yKaf** [comment]
AH, esti, fallait le lire pour catcher mon problem :^)

**Comment by S0yKaf** [comment]
change la ligne que j'ai dit pour ca `if team.captain_id != user_id and user_id != team_user.user_id:`

**Comment by pgrenaud** [comment]
Got it.
