### ISSUE TITLE
Réservation 10 min et décallage de temps

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#245]
Si un ordinateur est 2 minutes en retard sur l'heure du serveur, on voit 12min. Si c'est 2min en avance, on voit 8min etc.

Il faut que le serveur envoit le reserved_untill ainsi que son temps présent. Le timer sera parti avec ses infos.

Je n'ai pas le temps je fix le issue pour le moment, mais ceci avait été oublié.

**Comment by pgrenaud** [comment]
J'vais regarder ce que je peux faire.
