### ISSUE TITLE
J'aime pas la sécurity

### ISSUE THREAD

**Issue by jcanuel97** [lanmomo/lanmomo-website#248]
Veuillez valider votre courriel ! Contactez info@lanmomo.org si le courriel n'a pas été reçu.
Il s'affiche même avec un mot de passe
![image](https://cloud.githubusercontent.com/assets/15239708/10652864/042f34de-7828-11e5-9b9b-3c0a03e0f74e.png)
 invalide

**Comment by S0yKaf** [comment]
@deathocks qu'elle est la faile de securite selon toi?

**Comment by jdupl** [comment]
@deathocks ton courriel n'a pas été envoyé car ton courriel n'existe pas...
