### ISSUE TITLE
Switch Angular, Bootstrap and FontAwesome to their CDN

### ISSUE THREAD

**Issue by S0yKaf** [lanmomo/lanmomo-website#28]
instead of using local files.
- Bootstrap/FontAwesome -> http://www.bootstrapcdn.com/
- AngularJS -> https://developers.google.com/speed/libraries/devguide#angularjs

**Comment by jdupl** [comment]
Pourquoi? On risque d'avoir un bootstrap avec des couleurs personnalisées.

**Comment by S0yKaf** [comment]
j'aurais pense utiliser un theme deja fait, entk moi personnelement ca me tante pas de faire de CSS

**Comment by fxleblanc** [comment]
Pour le thème Kinimaro, j'avais pensé être le plus dans les couleurs de Montmorency, pour que ce soit cohérent avec le favicon que j'ai mis. Un genre de vert avec du noir. Dites-moi si vous êtes d'accord mais au pire un thème ca peut faire la job si on est serré dans le temps.

**Comment by S0yKaf** [comment]
ben je pense pas que ca va etre beau, tser le logo de momo est pas full sexy, imo on devrais design notre propre logo avec des couleurs plus interessante

**Comment by fxleblanc** [comment]
Pas de trouble. Je te laisse libre pour le front end.
