### ISSUE TITLE
Faire le backend de réservation des billets

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#3]
Faire en sorte que les joueurs puissent se créer un compte et limiter le nombre de place prédéfini.

Pour cette story, on veut seulement donner des "billets" aux gens et pas encore assigner des places prédéfinis.

**Comment by sbstp** [comment]
Bon j'imagine que le monde vont vouloir être assis prochent de leurs amis. Donc faudrait être capable de représenter plusieurs layouts de locaux. Suggestions?

**Comment by S0yKaf** [comment]
les places ca va etre la prochaine ittération

**Comment by jdupl** [comment]
Effectivement ça serait correct d'avoir juste une limite d'inscription.

**Comment by jdupl** [comment]
@petit-prince comment ça avance ?

**Comment by fxleblanc** [comment]
@jdupl Voici ce qui reste à faire(de mémoire) pour le backend:
-L'utilisateur recoit un message qui lui dit qu'un courriel lui a été envoyé quand il envoie la requête pour s'inscrire.
-Vérifier que l'utilisateur existe avant de confirmer l'inscription
-Envoyer un message si jamais le nombre d'inscription est atteint.

Sinon, toutes les fonctionnalités restantes sont au frontend(issue#4)

**Comment by S0yKaf** [comment]
je travailais sur valider le nombres de personne avec la config, pour pas que les gens puissent sign up si on a atteint le nombre maximal de gens.

il vas falloir aussi que les gens donnent leurs numero de telephones pour la securiter, donc ajouter ca dans le model

**Comment by fxleblanc** [comment]
@Kiniamaro, tu es sûr pour le téléphone, un courriel c'est assez je trouve.

**Comment by S0yKaf** [comment]
@petit-prince please J'ai parle au responsable des ressources Materiels aujourd'hui

**Comment by jdupl** [comment]
Si le cégep le demande, on a pas le choix @petit-prince

**Comment by fxleblanc** [comment]
Ok pour le num de téléphone alors.

**Comment by jdupl** [comment]
@petit-prince il manque le numéro de téléphone

**Comment by fxleblanc** [comment]
@jdupl ok pour le téléphone. Par contre, j'aimerais qu'on clarifie un peu l'état du "est-ce qu'on le fait ou pas". Je m'en remet à @Kiniamaro pour ça. C'est vraiment pas long le faire. Mais il va falloir modifier le front end(la vue partielle de subscription). Je vais faire une branche et le moment venu @Kiniamaro, tu feras des modifs directement dans ma branche pour modifier le front end à partir des changements(mineurs je dois dire) sur le backend.

**Comment by fxleblanc** [comment]
@Kiniamaro 
https://github.com/LanMomo/LanMomo-Website/tree/phone
