### ISSUE TITLE
Normaliser l'endroit des ressources statitiques

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#31]
Afin que je puisse créer les routes d'nginx il faudrait que toutes les ressources statiques (css, js, html etc.) ait un chemin qui commence soit par `public` ou `assets`.

Sinon, il faudrait préfixer la route de l'api par `/api/` afin de différencier les assets des requêtes à express.

La route d'nginx devrait soit être `/public/*` ou `^/api`. Il faudrait choisir le plus élégant.

**Comment by fxleblanc** [comment]
Toutes les ressources statiques(html, js, css) sont dans le dossier public. Le préfixe /api est déjà implémenté dans backend/routes/routes.js. Si jamais on utilise nginx pour gérer les fichiers statiques, on pourrait modifier app.js pour qu'express ne déclare pas le dossier.
