### ISSUE TITLE
Faire le frontend de réservation des billets

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#4]
- Afficher la liste des joueurs
- Afficher le nombre de places restantes
- Permettre de s'inscrire (vérification de courriels)

**Comment by SBSTP** [comment]
Comment est-ce qu'on représente les places? Comment on structure la "Map" dans la bd?

**Comment by jdupl** [comment]
Ben on pourrait tout de suite faire joueur <-> siège.
Pour l'instant la table siège aurait juste un id sans importance. On pourra ensuite ajouter des champs et la position physique de chaque siège.
@Kiniamaro

**Comment by SBSTP** [comment]
Bin c que la map risque de changer en fonction du local non? Faudrait être capable de représenter plusieurs layouts.

**Comment by jdupl** [comment]
Oh tu parles du positionnement de chaque siège ?
va voir #3 c'est la bonne story

**Comment by fxleblanc** [comment]
Voici ce qui reste à faire selon moi(de mémoire toujours, n'hésitez pas à contribuer):
-Plus belle page de présentation lorsque l'utilisateur réussit à s'inscrire(congratulations.html)
-Meilleure présentation des participants inscrits
