### ISSUE TITLE
Refaire fonctionner l'envoie de courriel

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#40]
ASAP
Le problème semble venir des changements faits pour les promises.

**Comment by fxleblanc** [comment]
## Problème

Le problème ne vient pas des promises. Si c'était le cas, on ne recevrait pas de réponse de la part du serveur car la méthode ne serait tout simplement pas appelée. Voici l'erreur envoyée par gmail.

```
{ [Error: Invalid login]
  cause: 
   { [Error: Invalid login]
     code: 'EAUTH',
     response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8 http://support.google.com/mail/bin/answer.py?answer=14257 184sm7112832qhc.39 - gsmtp',
     responseCode: 535 },
  isOperational: true,
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8 http://support.google.com/mail/bin/answer.py?answer=14257 184sm7112832qhc.39 - gsmtp',
  responseCode: 535 }
```

En faisant un peu de recherche, je suis tombé sur cette issue:
https://github.com/andris9/Nodemailer/issues/317

Dans notre cas, c'est peut-être le fait que l'on a fait des tests de courriels en localhost dans plusieurs endroits différents et que Gmail a juste pas aimé ça. 

## Solution

Il suffit simplement de changer le courriel. On pourrait se refaire un courriel de test juste pour le dev mais si on obtient une adresse de prod, aussi bien utiliser celle-là.

**Comment by jdupl** [comment]
Non @petit-prince arrête de me redire ça depuis 1 semaine. Essaye de changer de courriel.
Les infos se rendent pas bien dans le transporter.

**Comment by fxleblanc** [comment]
## Promises

Si tu regardes le commit https://github.com/LanMomo/LanMomo-Website/commit/f213ac9920dd9dadfc93a5954ee8112eeb747728, la promise était le problème avant. Mais comme je l'ai fix, tu vas recevoir une réponse du serveur qui te dit que ya une erreur avec l'envoi du courriel.

## Tests

Si jamais tu veux tester ce que je raconte, change le code pour utiliser les callbacks réguliers au lieu de la promise et tu obtiendras la même erreur. N.B. N'oublie pas de changer la config du transporter pour ne pas utiliser bluebird. C'est là que je fais la promisification.

## Config

La config se rend bien au transporter. Je t'invite à faire un console.log avant d'appeler la méthode transporter.sendMailAsync pour vérifier ce que je dis.

## Courriel

Au final, il suffit simplement de changer le courriel. Ça ne fait pas une semaine que je te dis ça. C'est vrai que la promise était le problème avant mais ce n'est plus le cas depuis le Hackoton. Pour tester, je vais prendre un compte temporaire mais comme j'ai dis dans ma réponse précédente, j'aimerais tester avec le compte de production éventuellement car il se peut que je doive changer la config pour envoyer le courriel à une adresse smtp custom.

## Références

https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyfunction-nodefunction--dynamic-receiver---function

**Comment by jdupl** [comment]
J'ai déjà fait des console.log. Fait juste utiliser un autre compte ça ne
fonctionne pas.

Utiliser gmail est une condition de succès du produit.

Contacte Patrick pour avoir le compte de prod, il ne veut pas m'écouter.
Promises

Si tu regardes le commit f213ac9
https://github.com/LanMomo/LanMomo-Website/commit/f213ac9920dd9dadfc93a5954ee8112eeb747728,
la promise était le problème avant. Mais comme je l'ai fix, tu vas recevoir
une réponse du serveur qui te dit que ya une erreur avec l'envoi du
courriel.
Tests

Si jamais tu veux tester ce que je raconte, change le code pour utiliser
les callbacks réguliers au lieu de la promise et tu obtiendras la même
erreur. N.B. N'oublie pas de changer la config du transporter pour ne pas
utiliser bluebird. C'est là que je fais la promisification.
Config

La config se rend bien au transporter. Je t'invite à faire un console.log
avant d'appeler la méthode transporter.sendMailAsync pour vérifier ce que
je dis.
Courriel

Au final, il suffit simplement de changer le courriel. Ça ne fait pas une
semaine que je te dis ça. C'est vrai que la promise était le problème avant
mais ce n'est plus le cas depuis le Hackoton. Pour tester, je vais prendre
un compte temporaire mais comme j'ai dis dans ma réponse précédente,
j'aimerais tester avec le compte de production éventuellement car il se
peut que je doive changer la config pour envoyer le courriel à une adresse
smtp custom.
Références

https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyfunction-nodefunction--dynamic-receiver---function

**Comment by fxleblanc** [comment]
Ok pour gmail. J'ai toujours été d'accord de changer de courriel ;). Je voulais juste mettre au clair que le problème était pas les promises. Je vais en parler à Patrick.

**Comment by jdupl** [comment]
Teste ton code avec un autre courriel ça fonctionne pas.......

**Comment by fxleblanc** [comment]
Oui. C'est ça qu'on se dit depuis tantôt. Y'a pas de trouble.

**Comment by jdupl** [comment]
Oui y'a un trouble ça fonctionne avec aucun courriel !

**Comment by fxleblanc** [comment]
Je sais que ça marche avec aucun courriel. J'ai peut-être pas été clair là-dessus. Je vais probablement essayer de le changer pour Oauth et voir si ça fonctionne car comme il est spécifié dans la issue andris9/Nodemailer#317, le problème est lié au auth avec user/pass et la position géographique. Quand je dis que y'a pas de trouble, je fais référence au fait que tu pensais que c'était les promises.

**Comment by jdupl** [comment]
Ne ferme PAS l'issue alors. Tu me disais «Au final, il suffit simplement de changer le courriel.».

**Comment by fxleblanc** [comment]
Ouais. J'ai mal fait mon affaire. C'est juste que je pensais qu'en répondant à la question des promises, ça serait finit. Je vais fix le auth et fermer la issue après.

**Comment by pgrenaud** [comment]
Update sur la situation ?

**Comment by fxleblanc** [comment]
WIP. Je vais utililser XOAUTH2 au lieu de user/pass pour le login.
