### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#43]
Ajouter une page de contact pour afficher un adresse courriel, liens vers la page facebook et autre. Pas besoin d'un formulaire pour l'instant.

**Comment by fxleblanc** [comment]
@pgrenaud Juste pour confirmer qu'on parle de la même page, c'est bien celle-là?

https://www.facebook.com/lanmomo/info?tab=page_info

voudrais-tu qu'on fasse un lien vers le reddit?

Aussi, pour le courriel, désolé je n'ai pas noté l'adresse officielle, pourrais-tu la noter dans cette issue-là?

**Comment by pgrenaud** [comment]
@petit-prince oui, quoi que le lien c'est simplement https://www.facebook.com/lanmomo
Reddit: https://www.reddit.com/r/lanmomo/
Email: info@lanmomo.ca

Si tu travailles sur cette page là, est-ce que tu peux la prendre à ton nom please?
