### ISSUE TITLE
Changer de favicon

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#45]
On devrait pas prendre le logo de Montmorency comme ça, on devrait avoir le notre.
On ne peut pas prendre le logo de Montmorency comme ça, on a pas les autorisations.

**Comment by jdupl** [comment]
@petit-prince

**Comment by fxleblanc** [comment]
Ok. On peut changer le logo. Pas de trouble.

**Comment by fxleblanc** [comment]
Qu'est-ce que vous proposez comme logo?

**Comment by pgrenaud** [comment]
On ne parle pas d'un logo, mais bien du favicon. Et je n'ai malheureusement rien à proposer.

**Comment by pgrenaud** [comment]
Aussi, vraiment important, déplacer le favicon à la racine du site (/public) pour éviter les 404. Les browser, même quand tu défini ton favicon dans ton html, on la mauvaise habitude de query `GET /favicon.ico` pour voir s'il n'aurait pas un favicon là. Donc, il faut aussi que le fichier soit un `.ico`.

**Comment by pgrenaud** [comment]
Need to fix favicon.

**Comment by jdupl** [comment]
- canal alpha
- triangle ~~illuminati~~ qui ressemble à illuminati

**Comment by pgrenaud** [comment]
Je garanti rien pour le triangle.

**Comment by jdupl** [comment]
^ voir edit

**Comment by jdupl** [comment]
closed by #95 
to be reopened if necessary
