### ISSUE TITLE
Faire le frontend des pages de jeux

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#5]
- Pages statiques allant chercher quelques infos sur le jeux.
- Administration des serveurs de jeu (et création de VMs?)
- Templates de config pour chaque jeu?

**Comment by sbstp** [comment]
est-ce que le monde vote pour quels jeux il va y avoir?

**Comment by jdupl** [comment]
Non

**Comment by Riboshom** [comment]
Il est essentiel de garder cette partie du site modulairee, étant donné que la plupart des jeux utilisent des protocoles différents pour l'administration à distance.
* Source engine games
  * [RCON](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol)
*  Minecraft
  *

**Comment by jdupl** [comment]
@Riboshom le frontend pourra être refait éventuellement. La tâche de base qu'on doit faire est vraiment simple. Je préfère jeter cette heure de travail rendu à la 2e itération que de passer 10 heures à faire un truc modulaire donc a pas encore les specs.

**Comment by Riboshom** [comment]
Mais les protocoles de communication, c'Est pas du backend stuff?

**Comment by jdupl** [comment]
Justement. Fais-toi un issue séparé pour ça. Tag ton issue avec le milestone m3 .

**Comment by Riboshom** [comment]
Oh, je croyais que c'était de ça qu'on parlait. Sorry.
