### ISSUE TITLE
Inclure le # de téléphone dans le frontend de réservation

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#51]

**Comment by fxleblanc** [comment]
En ce moment, dans la branche phones, le modèle est changé mais il reste à changer le front pour rajouter une boîte de texte dans le subscription.

**Comment by fxleblanc** [comment]
@Kiniamaro, voudrais-tu qu'on mette de la validation pour les phones?

**Comment by S0yKaf** [comment]
ouai faudrait

**Comment by S0yKaf** [comment]
added in #55
