### ISSUE TITLE
Mail is sent as "text/plain"

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#52]
This means that the user receive the confirmation mail this way:

> Veuillez confirmer votre courriel en cliquant &lt;a href=&quot;http://localhost:3000/api/verify/confirmation_key&quot;&gt;ici&lt;/a&gt;

When he should reveice it this way instead:

> Veuillez confirmer votre courriel en cliquant <a href="http://localhost:3000/api/verify/confirmation_key">ici</a>

So, we need to change the email header to "text/html" to fix the issue.

**Comment by S0yKaf** [comment]
fixed in #58
