### ISSUE TITLE
Déploiement avec forever

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#53]
## Commandes

sudo npm install -g forever
NODE_ENV=production forever start app.js

**Comment by jdupl** [comment]
y'a pas de moyen d'avoir moins de cheese ?

**Comment by pgrenaud** [comment]
On pourrait se tourner vers PM2 qui semble beaucoup plus complet.
- https://www.npmjs.com/package/pm2
- http://devo.ps/blog/goodbye-node-forever-hello-pm2/
- https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04

Still, ça reste du javascript.
