### ISSUE TITLE
Proposition de modèles

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#6]
## Utilisateur

-ID
-Prénom
-Nom
-Courriel
-Valide
-Gamer name
## Jeu

-ID
-Nom
-Description
-Image (logo)
-Liste de Serveur(Voir serveur)
## Serveur

-ID
-Adresse IP
-Port
-Nom de domaine
-Maximum de joueurs
-Mode de jeux
-Description
## Event

-ID
-Places
-Date
-Location
-Serveurs (sous entendu jeux)

**Comment by jdupl** [comment]
Il manque le courriel d'un utilisateur.

**Comment by jdupl** [comment]
Il manque la confirmation d'un user (si le courriel a été validé ou non).

Sinon :+1:
