### ISSUE TITLE
Terms page

### ISSUE THREAD

**Issue by S0yKaf** [lanmomo/lanmomo-website#60]
Il nous faut une page de règle qui a de l'allure, donc si quelqu'un se connais bien en "Legal stuff" s'il-vous-plait manifester vous!

**Comment by pgrenaud** [comment]
Je vais prendre la peine de passer par là quand je vais faire ma proposition pour le UI. Still, comme tu as dit, si quelqu'un se connait en légal, ça serait bien de nous donner un coup de main.

**Comment by jdupl** [comment]
- pas d'abus internet
- pas de drogues ni alcool
- nous sommes pas responsable des objets perdus ou volés

**Comment by S0yKaf** [comment]
- Faire preuve de respect envers tout les participants
- Respecter les décisions de l`organisation

**Comment by RickyNotaro** [comment]
On peux s'inspirer de ceux du LanETS: http://www.lanets.ca/terms

**Comment by pgrenaud** [comment]
Renommer la page `/rules` pour `/terms`.
