### ISSUE TITLE
Add proper logging

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#63]
Add proper logging (and remove all `console.log` calls) before the first milestone release. Multiple solutions are available.

Middlewares:
- [Morgan](https://github.com/expressjs/morgan): HTTP request logger for express.

Logger:
- [winston](https://github.com/winstonjs/winston): Multi-transport async logging library.
- [Scribe.js](https://github.com/bluejamesbond/Scribe.js): Lightweight NodeJS Logging.
- [log4js-node](https://github.com/nomiddlename/log4js-node): Port of log4js to node.js.

**Comment by jdupl** [comment]
:-1: pour logger dans un fichier.
On log dans sysout linux pipe ça dans un fichier. 
Par contre, ça peut être une lib de logging qui log vers stdout.

**Comment by jdupl** [comment]
fixed by #87
