### ISSUE TITLE
Enlever le 404 http://dev.lanmomo.ca/{{game.imagePath}}

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#66]
Je ne sais pas d'où ça vient.

**Comment by S0yKaf** [comment]
wtf?, ou?

**Comment by pgrenaud** [comment]
Je l'ai déjà fix sur ma branche.

**Comment by S0yKaf** [comment]
@pgrenaud, j'aimerais quand meme savoir ca sort d'ou

**Comment by pgrenaud** [comment]
Fixed in ad98580d76f378ec293be201d2e4f1e51cf34aca

**Comment by pgrenaud** [comment]
Si vous voulez le fix maintenant, je peux faire un PR avec juste ça.

**Comment by S0yKaf** [comment]
pourtant les images affichaient

**Comment by pgrenaud** [comment]
@Kiniamaro lit la doc et comprend pourquoi: https://docs.angularjs.org/api/ng/directive/ngSrc

**Comment by S0yKaf** [comment]
alright funny stuff

**Comment by jdupl** [comment]
closed by #69
