### ISSUE TITLE
no backend field validation on signup

### ISSUE THREAD

**Issue by S0yKaf** [lanmomo/lanmomo-website#67]
the backend currently only checks if a field exists and does not look if for instance, `email` really is an email.

someone could easily bypass de frontend validation and write whatever he wishes and it would be valid in the backend assuming all the fields are there.

**Comment by pgrenaud** [comment]
Ha ha ha ha ha ha! I was just writing the same issue as yours! Yes, you are indeed right on that. And that need to be fixed before the first release.

We need to ensure a few things here:
- Validate each field to ensure that they correspond to its type (is `email` really a valid email address?)
- Validate each field to ensure that they do not contains invalid character (see my next point)
- Ensure that we are protected against SQL injection and XSS (are metacharacters properly escaped?)
- Ensure that emails and username are unique (two participants cannot use the same email/username)
