### ISSUE TITLE
Proposition de l'api REST

### ISSUE THREAD

**Issue by fxleblanc** [lanmomo/lanmomo-website#7]
## Les utilisateurs

GET /api/users
GET /api/users/id
GET/POST /api/users/register
GET/POST /api/users/login
## Les jeux

GET /api/games
GET /api/games/id
## Les serveurs

GET /api/servers
GET /api/servers/id
GET /api/servers/id/games/id

**Comment by jdupl** [comment]
Il faudrait un moyen de register un user

**Comment by jdupl** [comment]
On va y aller avec ça pour commencer. Faut accélerer le processus un peu.

**Comment by sm-Fifteen** [comment]
Login en REST? C'est pas stateless, ça, ça prendrait des authentication tokens, non?

**Comment by jdupl** [comment]
On est pas rendu au login @Riboshom, mais oui

**Comment by S0yKaf** [comment]
see -> #14
