### ISSUE TITLE
More complete email template

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#70]
Something like:

> Bonjour {{firstname}},
> 
> Veuillez confirmer votre courriel en cliquant sur le lien suivant:
> &lt;a href=&quot;{{url}}&quot;&gt;{{url}}&lt;/a&gt;
> 
> Merci et à bientôt!
> 
> &lt;small&gt;Ceci est un couriel envoy&eacute; automatiquement. Veuillez ne pas y r&eacute;pondre.&lt;/small&gt;

**Comment by fxleblanc** [comment]
@pgrenaud 0fcae454de0588cd9742e601ce50c74fcb74ca58

**Comment by pgrenaud** [comment]
@petit-prince Au lieu de pull le user de la db, fait juste le passé l'objet user en paramètre comme tu le faire avec emailVerification. Donc, fait `var sendMail = function(req, res, user, emailVerification) {...}` et on va évité de query la bd pour rien.

**Comment by pgrenaud** [comment]
Aussi, pas moyen de mettre le template ailleurs que direct dans le controller ? Genre dans la config ou dans une vue ?

**Comment by jdupl** [comment]
@pgrenaud on va éviter de bloat la config là.
On veut juste que le site soit livrable le plus rapidement possible. On ne réutilise pas le template de courriel alors je ne vois pas assez d'intérêt pour le moment de séparer ça.

**Comment by pgrenaud** [comment]
@petit-prince Si tu travailles sur cette issue là, est-ce que tu peux la prendre à ton nom please?

**Comment by fxleblanc** [comment]
Ok pour le user en paramètre et pour la template dans la config. Tu as raison, à l'avenir, quand je vais travailler sur quek chose, je vais me mettre en assignee mais préfères-tu que je t'avertisses sur chat ou directement dans l'issue?

**Comment by pgrenaud** [comment]
@petit-prince c'est sur que idéalement tu le demande avant, mais j'étais pas là anyway. Dans le contexte actuelle, t'aurais juste du le mettre à ton nom. Dans tout les cas, ne travaille pas sur qqch qui est assigné à qqun d'autre.

**Comment by jdupl** [comment]
@pgrenaud comme je t'ai dit sur slack, tu t'es tout assigné...
