### ISSUE TITLE
Credit the Photographer

### ISSUE THREAD

**Issue by S0yKaf** [lanmomo/lanmomo-website#74]
the photographer wanted us to credit her DeviantArt for the photos, We could add it in the `footer` or `about us` page.

http://cosphobuddy.deviantart.com/

**Comment by pgrenaud** [comment]
Yep, I still haven't finished with the UI. I'll do that.

**Comment by S0yKaf** [comment]
guess we can't have more than 1 person on issues at a time :\

**Comment by jdupl** [comment]
closed by #103
