### ISSUE TITLE
Éviter l'injection de scripts

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#75]
Tester si l'injection de js et html est possible.

**Comment by fxleblanc** [comment]
Pour valider les données reçues du front-end, on pourrait utiliser ca:
https://github.com/ctavan/express-validator

L'autre avantage possible de la technologie à part la sécurité est que l'on pourrait enlever la condition qui vérifie le corps de la requête dans la méthode post api/subscribe puisque la librairie vérifie chaque paramètre de la requête selon une validation de base ou personnalisée.
