### ISSUE TITLE
Rappel des choses à apporter au Lan

### ISSUE THREAD

**Issue by RickyNotaro** [lanmomo/lanmomo-website#79]
# Liste de choses à apporter au LAN Montmorency

Il serait bien d'avoir une page qui indique les choses à apporter au lan, car présentement le seul endroit où il y a cette information, c'est la barre alert-info sur la page d'[inscription](http://dev.lanmomo.ca/subscribe/).
- ordinateur
- écran
- clavier 
- souris
- tapis de souris
- casque d'écoute
- câble réseau 
- barre d'alimentation

**Comment by S0yKaf** [comment]
genre ca? ;)
![2015-03-20-210554_1186x300_scrot](https://cloud.githubusercontent.com/assets/3664099/6763105/f611c79a-cf44-11e4-870e-6b68af1af20b.png)

**Comment by RickyNotaro** [comment]
Oui, mais il faudrait l'indiquer à un autre endroit que à l'inscription.

**Comment by S0yKaf** [comment]
faudrais voir ou, mais je pense que les gens savent c quoi un lan maintenant, on pourrais l'ecrire sur facebook

**Comment by RickyNotaro** [comment]
On a un outils pour envoyer des emails ? (style mailing list ? ) 
On pourrais envoyer un email avant le lan pour faire un rappel de tout.

**Comment by jdupl** [comment]
Oui, mais on pourrait envoyer les courriels à la main. 

On peut envoyer un courriel qui confirme que tu inscription est confirmée et qui dit quoi apporter encore.

**Comment by pgrenaud** [comment]
Déjà que je pensais revoir le template du courriel (voir #70), je pourrais y ajouter ça oui. Sinon, en effet, il faut anyway inscrire ça quelque part. Je pense renommer la page `/rules` pour `/terms` et y mettre tout ça là dedans, sous forme de sections (conditions, règlements, responsabilité, etc.)

**Comment by jdupl** [comment]
Je propose qu'on envoie un courriel avant le LAN pour rappeler aux gens ce qu'ils doivent apporter.

On peut aussi ajouter ça dans le template du courriel. Des messages différents pour console et PC ne sont pas nécessaires. On peut juste tout spam dans un message.

**Comment by pgrenaud** [comment]
Rendu là, on peut simplement envoyer un courriel avant le lan et ne pas toucher au template. Comme ça, on a rien à faire avec ça pour m3.

**Comment by jdupl** [comment]
Ouai je proposais ça comme "bonus".

**Comment by pgrenaud** [comment]
Je préfère ne pas mettre ça dans le template. Surtout que c'est le mail de confirmation, il n'est pas encore inscrit. On pourrait envoyé un autre mail une fois confirmer, mais c'est, c'est un autre issue pour un autre milestone.

**Comment by pgrenaud** [comment]
Anyway, pour répondre à la issue, je vais ajouter ça qqpart dans la page de terms, quand je vais faire #60.

**Comment by fxleblanc** [comment]
@pgrenaud je suis partant pour le courriel de "félicitations" après que le user se soit inscrit. Je vais faire un issue dans m4

**Comment by jdupl** [comment]
Ça me va que les infos soient un courriel de confirmation après que l'utilisateur ait cliqué le lien de confirmation. On pourrait essayer m4, mais je crois que ça va attendre à m5.

**Comment by jdupl** [comment]
voir #100

**Comment by sm-Fifteen** [comment]
"Ceux qui n'ont pas de tapis de souris se verront attribuer le mousepad of shame"

**Comment by pgrenaud** [comment]
On retrouve la liste sur la page `/terms`.
