### ISSUE TITLE
Infos de serveurs

### ISSUE THREAD

**Issue by sm-Fifteen** [lanmomo/lanmomo-website#8]
Ajouter les informations de base (live) des serveurs de jeux tel que le nombre de jeux, la map courante etc. via des requêtes serveur [A2S](https://developer.valvesoftware.com/wiki/Master_Server_Query_Protocol).

Une recherche sommaire menée à cet égard propose d'utiliser Holiverh/python-valve pour les jeux Source, une librairie qui, en plus d'être toujours maintenue, offre un support du protocole RCON (variante de Valve) ce qui simplifirait l'implémentation éventuelle d'une backent d'administratioin de serveurs à la manière de [HLSW](http://www.hlsw.org/hlsw/information/).

AES est un protocole extrèmement commun pour effectuer des requêtes de status aux serveurs. Pour les jeux utilisant d'autres protocoles, comme Gamespy (Minecraft, ARMA2, UT99, UT3), UT2 query protocol (UT2004, Killing Floor), etc. il sera nécéssaire d'inclure des librairies supplémentaires.

Voir [cette liste](https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v2) pour savoir quel query protocol s'applique à quel jeu.
Note additionelle : Minecraft utilise RCON (Source) pour l'administration et GameSpy v4 pour les requêtes de status.

**Comment by jdupl** [comment]
@Riboshom tu pourrais commencer un projet de ton côté qui implémente la récupération des infos de serveurs.
Ton service serait dans le même réseau que les serveurs  de jeux durant le LAN. Chaque X secondes, le service enverrait une notification au serveur qui héberge le vrai site du LAN.
Les joueurs auraient donc les infos des serveurs sur le site du  LAN.

**Comment by sm-Fifteen** [comment]
Closed - Fonctionnalité réassignée au server-notifier.

**Comment by jdupl** [comment]
Il faut faire le frontend dans le site web. Je vais faire un issue pour clarifier.
