### ISSUE TITLE
Afficher les jeux de consoles

### ISSUE THREAD

**Issue by jdupl** [lanmomo/lanmomo-website#82]
Avoir une section (ou pas) pour les jeux console.

**Comment by pgrenaud** [comment]
Je pourrais ajouter une section sur la page des jeux, en dessous des jeux PC. Est-ce qu'on a une idée des jeux en question?

**Comment by S0yKaf** [comment]
- Smash (most of em)
- TowerFall (ouya)

**Comment by fxleblanc** [comment]
Pour les jeux de consoles, à date, je vois pas mal juste Smash Bros Melee, Brawl et Project M.

**Comment by jdupl** [comment]
donc:
- tower fall
- smash melee
- smash project M ?

**Comment by S0yKaf** [comment]
@jdupl TowerFall

**Comment by jdupl** [comment]
closed by #102
